name : hello world 
on: push
jobs:
  print-information:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
      - name: print registration No
        run: echo "711322110018
      - name: print name 
        run: echo "Harish"
     
